In [15]:
import numpy as np

In [18]:
A = np.array([[0,1], [2,3], [4,5]])
B = np.array([[0,1,2,3], [4,5,6,7]])

C = np.dot(A, B)
print(C)

x = C.max()
print(f'最大値: {x}')

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47


In [19]:
D = np.arange(6).reshape(3,2)
E = np.arange(8).reshape(2,4)

F = np.dot(D, E)
print(F)

y = F.max()
print(f'最大値: {y}')

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
